### ISSUE TITLE
Analytics conflicting with Google Analytics Dashboard

### ISSUE THREAD

**Issue by Lefthandmedia** [yogoo/Analytics#10]
Hi,
I seem to get a conflict between Google Analytics Dashboard v1.0.1 EXTRA(http://modx.com/extras/package/googleanalyticsdashboardwidget) 
and Analytics EXTRA(http://modx.com/extras/package/analytics).

see
http://forums.modx.com/thread/90947/google-analytics-dashboard-conflicting-with-analytics#dis-post-498106

**Comment by yogoo** [comment]
Hi, please see the closed issue #1 about this.

**Comment by Lefthandmedia** [comment]
I understand. 
But still think "Analytics" is a too general namespace. why not "Yogoo_Analytics" or something.
There are bound to be more extra's relating to analytics (and not only Google).

**Comment by yogoo** [comment]
ha you're quick to resond, I posted a short answer on why Analytics on the forum.

Prefixing with a username is not an option as it ties the extra to a physical person. Code can be written by a team or change hands. Breadcrumbs and sitemapFriend are good examples for this. So prefixing with a username is not a long term option.

I understand you consider "Analytics" to be too generic, however the namespace follows the naming conventions for a Modx extra. As stated in reply to issue #1, I won't change it to something random because another dev doesn't respect the naming convention. This would only create a terrible mess on the long run.

I'll recommend you turn to the developer of Google Analytics Dashboard Widget and ask him to use a namespace that follows the naming conventions. That's a very simple and transparent operation for him to do with no impact whatsoever.

**Comment by Lefthandmedia** [comment]
Hi,

I also posted this with Sterc, the guys that made Google Analytics  Dashboard Widget. but they just don’t respond. Thanks for responding.
Maybe a more descriptive name in the class file would help. or classname.

**Comment by withoutfanfare** [comment]
I noticed this also. The naming could be AnalyticsTracker or AnalyticsTag which would be more descriptive of what it does because it doesn't provide analytics as such - only tracking.

**Comment by yogoo** [comment]
Thanks for the input. I stopped Modx developement a while ago and this extra is not maintained anymore. This won't be fixed. Feel free to fork.
