### ISSUE TITLE
Respect Do not track HTTP headers

### ISSUE THREAD

**Issue by DisobedientMedia** [yogoo/Analytics#4]
With new EU cookie laws now in effect, it would be a useful feature if the analytics function respected the Users 'Do Not Track' browser settings

A function to do that, taken from http://robert-lerner.com/do-not-track-headers-in-php.php

``` php
function do_not_track() {
  if (isset($_SERVER['HTTP_DNT'])) {
    if ($_SERVER['HTTP_DNT']==1) {
      RETURN TRUE;
    }
  } elseif (function_exists('getallheaders')) {
    foreach (getallheaders() as $k => $v) {
      if (strtolower($k)==="dnt" && $v==1) {
        RETURN TRUE;
      }
    }
  }
  RETURN FALSE;
}
```

Looking at the Analytics.php code, you already have the ability to not track a manager user. Could this be extended for the DNT header?

It may be nice to make the DNT feature an optional parameter in the snippet call.

**Comment by yogoo** [comment]
Thank you for your feedback and for taking the time to post the code and the source of it.

You're bringing up a couple of very important points that desserve more than a short answer on why I will not integrate this [great] code into Analytics. This is intended to be an open discussion rather than a closed decision.

1.- EU Cookie Law

Given the public information available at the time of writing, compliance to the EU cookie is a whole different topic than DNT compliance. And here is why:
- The cookie law required a website owned by an EU company and targeted to and EU audience to request the implicit consent of a user to use cookies. Any type of cookies, not only analytics cookies. Complying to the DNT Header would not make a website compliant with the EU Cookie law.
- [The EU Cookie law was amended](http://www.guardian.co.uk/technology/2012/may/26/cookies-law-changed-implied-consent) at the last minute (well almost) to include "implicit consent of the user". However users should still be informed of the use of cookies and else. Here we fall into privacy policy and terms of use rather than DNT compliance.
- Lastly DNT compliance is not part of the EU Cookie law, so implementing such a feature based on this argument would be misleading the community.
- If compliance to the EU Cookie law is a concern for you, I'd recommend to use a service such as [The Cookie Collective](http://www.cookielaw.org) to audit your website and make it 100% compliant in a snap.

2.- DNT header compliance

By Mozilla's own words, the [DNT header is intended « to let a website know when they [users] would like to opt-out of third-party tracking for behavioral advertising »](https://wiki.mozilla.org/Privacy/Jan2011_DoNotTrack_FAQ). Google Analytics does not fall into the third-party services for which the DNT header is intended. Let me add these points:
- The industry moves toward DNT support by third-party services rather than by website developers. This makes sense as a user might want to opt-out only from specific third-party tracking while opting-in from other services. Blocking third-party tracking on a site by site basis clearly isn't a scalable solution as it would very quickly become unmanageable for both users and developers. That's most likely why the DNT header will replace ad-blocking browser plugins (global vs local solution).
- Google already offers ways to [opt-out from Google Analytics](https://tools.google.com/dlpage/gaoptout?hl=en) from any major browser. And browser plugins such as [ghostery](http://www.ghostery.com/) offer a very comprehensive way to tackle the issue until the industry will be fully compliant.
- Yahoo and Adobe analytics already respect the DNT header and it's most likely a matter of time before Google does it natively as well.

I hope this explanation clears up the topic a bit and if you still think Analytics should offer a way to comply with DNT headers, I'll be happy to hear your arguments.

**Comment by DisobedientMedia** [comment]
Excellent response, thanks for taking the time to explain it so well. Totally agree with all your points. Closing the issue
